### ISSUE TITLE
SendGroupMessage时低概率会panic

### ISSUE THREAD

**Issue by Sora233** [Mrs4s/MiraiGo#180]
可以看到是(*ServiceElement).Pack(0x0, 此处ServiceElement为0x0，但我代码中未使用ServiceElement，且发送前我会检查是否有Element是nil，因此怀疑是线程不安全导致的问题。
此问题大约几天至十几天会出现一次。
```
goroutine 326749 [running]:
runtime/debug.Stack(0xc000ba5100, 0xd8aa00, 0x1612b90)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/Sora233/DDBOT/lsp.(*Lsp).ConcernNotify.func2.1(0xc002c32490)
        /home/ubuntu/go/src/github.com/Sora233/DDBOT/lsp/notify.go:92 +0x76
panic(0xd8aa00, 0x1612b90)
        /usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/Mrs4s/MiraiGo/message.(*ServiceElement).Pack(0x0, 0x1027420, 0x0, 0x7fac7ffce0a8)
        /home/ubuntu/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20210810070836-6614d2383adb/message/pack.go:84 +0x37
github.com/Mrs4s/MiraiGo/message.ToProtoElems(0xc002abf560, 0x1, 0x1, 0xc000ba5501, 0x48a41f, 0xd77fa0, 0xc004f909f0)
        /home/ubuntu/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20210810070836-6614d2383adb/message/message.go:285 +0x59a
github.com/Mrs4s/MiraiGo/client.(*QQClient).buildGroupSendingPacket(0xc0002ad680, 0x13645718, 0x162cb15ec, 0x0, 0x0, 0xc002abf560, 0x1, 0x1, 0xc00481abc8, 0xc008686690, ...)
        /home/ubuntu/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20210810070836-6614d2383adb/client/group_msg.go:242 +0x17b
github.com/Mrs4s/MiraiGo/client.(*QQClient).sendGroupMessage(0xc0002ad680, 0x13645718, 0xc000ba5700, 0xc000ba5790, 0x0)
        /home/ubuntu/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20210810070836-6614d2383adb/client/group_msg.go:128 +0x86c
github.com/Mrs4s/MiraiGo/client.(*QQClient).SendGroupMessage(0xc0002ad680, 0x13645718, 0xc0023622e8, 0x0, 0x0, 0x0, 0x4)
        /home/ubuntu/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20210810070836-6614d2383adb/client/group_msg.go:54 +0x333
github.com/Sora233/DDBOT/lsp.(*Lsp).sendGroupMessage.func2(0xc0050812a0)
        /home/ubuntu/go/src/github.com/Sora233/DDBOT/lsp/module.go:489 +0x65
github.com/Sora233/DDBOT/utils.Retry(0x2, 0x1dcd6500, 0xc000ba5900, 0xf368e0)
        /home/ubuntu/go/src/github.com/Sora233/DDBOT/utils/utils.go:159 +0x54
github.com/Sora233/DDBOT/lsp.(*Lsp).sendGroupMessage(0xc000034d00, 0x13645718, 0xc0023622e8, 0x92910b)
        /home/ubuntu/go/src/github.com/Sora233/DDBOT/lsp/module.go:488 +0x15e
github.com/Sora233/DDBOT/lsp.(*Lsp).sendChainGroupMessage(0xc000034d00, 0x13645718, 0xc00481ab48, 0x1, 0x1, 0x46c354, 0xc001ce4f00, 0xc000135710)
        /home/ubuntu/go/src/github.com/Sora233/DDBOT/lsp/module.go:515 +0x8e
github.com/Sora233/DDBOT/lsp.(*Lsp).ConcernNotify.func2(0xc000034d00, 0xc002c32490, 0x1039f98, 0xc0034ff840, 0xc00481ab48, 0x1, 0x1, 0x1039fd8, 0xc002bbaea0, 0xc0023622d0, ...)
        /home/ubuntu/go/src/github.com/Sora233/DDBOT/lsp/notify.go:96 +0xea
created by github.com/Sora233/DDBOT/lsp.(*Lsp).ConcernNotify
        /home/ubuntu/go/src/github.com/Sora233/DDBOT/lsp/notify.go:88 +0xb57
```

**Comment by wdvxdr1123** [comment]
原因为长消息上传失败，目前不清楚具体的失败原因
link Mrs4s/go-cqhttp#1001  Mrs4s/go-cqhttp#1006

**Comment by Mrs4s** [comment]
请试一下最新的commit, 我给长消息上传失败的地方加了 `log` 事件
