### ISSUE TITLE
[bug?]发送@x\n图片失败，嘤嘤嘤

### ISSUE THREAD

**Issue by icarus-ai** [Mrs4s/MiraiGo#205]
打印element:
*message.AtElement, &{****** @　 false}
*message.TextElement, &{
}
*message.GroupImageElement, &{{****-C764-E47B-48EE-0793EEE7A5F4}.PNG 31238**** 1000 0 53531 561 680 [*** 245 37 *** 199 100 *** 123 72 238 7 147 238 231 165 ***] https://gchat.qpic.cn/gchatpic_new/1/0-0-***********/0?term=2 0 false}
打印message.EstimateLength: 105

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2bf69c]

goroutine 91 [running]:
github.com/RomiChan/protobuf/proto.encodeBool({0x14f2000, 0x39, 0x1be}, 0x0, 0x2)
	/home/my/pkg/mod/github.com/!romi!chan/protobuf@v0.0.0-20211126082632-0d67337f63d4/proto/bool.go:24 +0x34
github.com/RomiChan/protobuf/proto.pointerEncodeFuncOf.func1({0x14f2000, 0x39, 0x1be}, 0x188437c, 0x0)
	/home/my/pkg/mod/github.com/!romi!chan/protobuf@v0.0.0-20211126082632-0d67337f63d4/proto/pointer.go:37 +0x64
github.com/RomiChan/protobuf/proto.structEncodeFuncOf.func1({0x14f2000, 0x5, 0x1be}, 0x1884310, 0x2)
	/home/my/pkg/mod/github.com/!romi!chan/protobuf@v0.0.0-20211126082632-0d67337f63d4/proto/struct.go:271 +0x210
github.com/RomiChan/protobuf/proto.pointerEncodeFuncOf.func1({0x14f2000, 0x5, 0x1be}, 0x140df60, 0x2)
	/home/my/pkg/mod/github.com/!romi!chan/protobuf@v0.0.0-20211126082632-0d67337f63d4/proto/pointer.go:37 +0x64
github.com/RomiChan/protobuf/proto.structEncodeFuncOf.func1({0x14f2000, 0x3, 0x1be}, 0x140df60, 0x2)
	/home/my/pkg/mod/github.com/!romi!chan/protobuf@v0.0.0-20211126082632-0d67337f63d4/proto/struct.go:271 +0x210
github.com/RomiChan/protobuf/proto.pointerEncodeFuncOf.func1({0x14f2000, 0x3, 0x1be}, 0x1838df0, 0x2)
	/home/my/pkg/mod/github.com/!romi!chan/protobuf@v0.0.0-20211126082632-0d67337f63d4/proto/pointer.go:37 +0x64
github.com/RomiChan/protobuf/proto.sliceEncodeFuncOf.func1({0x14f2000, 0x0, 0x1be}, 0x18679b0, 0x2)
	/home/my/pkg/mod/github.com/!romi!chan/protobuf@v0.0.0-20211126082632-0d67337f63d4/proto/slice.go:71 +0x1cc
github.com/RomiChan/protobuf/proto.structEncodeFuncOf.func1({0x14f2000, 0x0, 0x1be}, 0x18679b0, 0xa)
	/home/my/pkg/mod/github.com/!romi!chan/protobuf@v0.0.0-20211126082632-0d67337f63d4/proto/struct.go:281 +0x2cc
github.com/RomiChan/protobuf/proto.pointerEncodeFuncOf.func1({0x14f2000, 0x0, 0x1be}, 0x18679b0, 0x9)
	/home/my/pkg/mod/github.com/!romi!chan/protobuf@v0.0.0-20211126082632-0d67337f63d4/proto/pointer.go:37 +0x64
github.com/RomiChan/protobuf/proto.Marshal({0x65fe30, 0x18679b0})
	/home/my/pkg/mod/github.com/!romi!chan/protobuf@v0.0.0-20211126082632-0d67337f63d4/proto/proto.go:21 +0xc0
github.com/Mrs4s/MiraiGo/internal/proto.Marshal(...)
	/home/my/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20211126022251-e8e50b5062b1/internal/proto/wrapper.go:8
github.com/Mrs4s/MiraiGo/message.(*ForwardMessage).CalculateValidationData(0x15b7c04, 0x1f02, 0x271521bf, 0x19b9d4f8)
	/home/my/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20211126022251-e8e50b5062b1/message/forward.go:113 +0x1c8
github.com/Mrs4s/MiraiGo/client.(*QQClient).uploadGroupLongMessage(0x15e1680, 0x19b9d4f8, 0x15b7c04)
	/home/my/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20211126022251-e8e50b5062b1/client/group_msg.go:166 +0x11c
github.com/Mrs4s/MiraiGo/client.(*QQClient).SendGroupMessage(0x15e1680, 0x19b9d4f8, 0x140de70, {0x0, 0x0, 0x0})
	/home/my/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20211126022251-e8e50b5062b1/client/group_msg.go:55 +0x268
botapi/api/api.SendGroupMessage(0x15e1680, 0x19b9d4f8, {0x620400, 0x140de60})
	/home/my/botapi/api/api.go:673 +0x1b4

**Comment by icarus-ai** [comment]
艹 大概是我QQ风控了 自闭

**Comment by icarus-ai** [comment]
另一个号正常

**Comment by icarus-ai** [comment]
另一个号发三张图的富文本消息也nil

**Comment by icarus-ai** [comment]
golite修好了 [proto: fix deref nil in sizeOfBool and encodeBool](https://github.com/RomiChan/protobuf/commit/88609480c75a16f6bcb6ee815fc7f9772ff8b506)
