### ISSUE TITLE
Segmentation violation

### ISSUE THREAD

**Issue by orzogc** [Mrs4s/MiraiGo#42]
bot正常运行几个小时后就出现下面的panic：
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5bc3e5]

goroutine 16 [running]:
net.(*TCPConn).Write(0x0, 0xc0020c5680, 0x204, 0x280, 0x280, 0xb9b901, 0xc00203d1b0)
        <autogenerated>:1 +0x5
github.com/Mrs4s/MiraiGo/client.(*QQClient).send(...)
        /home/orzogc/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200918070115-5c4991c14f5b/client/client.go:939
github.com/Mrs4s/MiraiGo/client.(*QQClient).registerClient(0xc000110dc0)
        /home/orzogc/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200918070115-5c4991c14f5b/client/client.go:911 +0x67
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop(0xc000110dc0)
        /home/orzogc/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200918070115-5c4991c14f5b/client/client.go:993 +0x4f1
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).Login
        /home/orzogc/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200918070115-5c4991c14f5b/client/client.go:186 +0x92
```

**Comment by Mrs4s** [comment]
应该修复了，请再试试？

**Comment by orzogc** [comment]
没修复，还是panic
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5bc3e5]

goroutine 16 [running]:
net.(*TCPConn).Write(0x0, 0xc000452a00, 0x204, 0x280, 0x280, 0xba5b01, 0xc0032521f0)
        <autogenerated>:1 +0x5
github.com/Mrs4s/MiraiGo/client.(*QQClient).send(...)
        /home/orzogc/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200919153352-249af274638d/client/client.go:958
github.com/Mrs4s/MiraiGo/client.(*QQClient).registerClient(0xc000110dc0)
        /home/orzogc/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200919153352-249af274638d/client/client.go:930 +0x67
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop(0xc000110dc0)
        /home/orzogc/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200919153352-249af274638d/client/client.go:1011 +0x4f1
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).Login
        /home/orzogc/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200919153352-249af274638d/client/client.go:189 +0x92
```
最奇怪的是只有服务器上的才会panic，我自己PC上的从来不会，go的版本和代码都是一样的。

**Comment by orzogc** [comment]
建议复杂的goroutine内部用`recover()`处理panic，不然出现panic整个程序跟着崩溃

**Comment by Mrs4s** [comment]
能否给下日志的上下文并打开debug，该问题为网络问题 如果在此处使用 `recover()` 将会在后续代码造成更加难以预料的错误.

**Comment by Mrs4s** [comment]
已修复
