### ISSUE TITLE
加载好友列表出现panic

### ISSUE THREAD

**Issue by orzogc** [Mrs4s/MiraiGo#47]
应该是10月5日的更新导致的，4日的 43db052ad6e4e483aaf449402c9800a9190b9aaf 没有问题。
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9d6f25]

goroutine 1 [running, locked to thread]:
github.com/Mrs4s/MiraiGo/binary.(*TEA).encode(0x0, 0xc0001987e0, 0x8, 0xe0, 0xc0001987e0, 0x8, 0xe0)
        /home/orzogc/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20201006103627-071d50aec7f1/binary/tea.go:124 +0x45
github.com/Mrs4s/MiraiGo/binary.(*TEA).Encrypt(0x0, 0xc0003d7400, 0xd6, 0x121, 0xc000010578, 0xc000010578, 0xc0008879e0)
        /home/orzogc/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20201006103627-071d50aec7f1/binary/tea.go:44 +0x1ee
github.com/Mrs4s/MiraiGo/binary.(*Writer).EncryptAndWrite(0xc000010570, 0x0, 0x0, 0x0, 0xc0003d7400, 0xd6, 0x121)
        /home/orzogc/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20201006103627-071d50aec7f1/binary/writer.go:68 +0x71
github.com/Mrs4s/MiraiGo/protocol/packets.BuildUniPacket.func1(0xc000010570)
        /home/orzogc/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20201006103627-071d50aec7f1/protocol/packets/builders.go:35 +0x225
github.com/Mrs4s/MiraiGo/binary.(*Writer).WriteIntLvPacket(0xc00045d650, 0x4, 0xc00045d680)
        /home/orzogc/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20201006103627-071d50aec7f1/binary/writer.go:74 +0x7b
github.com/Mrs4s/MiraiGo/protocol/packets.BuildUniPacket(0x78ad861d, 0xc000123637, 0xc9dae3, 0x1d, 0xc00042c001, 0xc0001661c8, 0x4, 0x4, 0xc00045d7bc, 0x0, ...)
        /home/orzogc/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20201006103627-071d50aec7f1/protocol/packets/builders.go:29 +0x1a5
github.com/Mrs4s/MiraiGo/client.(*QQClient).buildFriendGroupListRequestPacket(0xc000172300, 0x960000, 0xc00045d8d0, 0xad0a98, 0x1273d20, 0x1273d28)
        /home/orzogc/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20201006103627-071d50aec7f1/client/builders.go:363 +0x54a
github.com/Mrs4s/MiraiGo/client.(*QQClient).GetFriendList(0xc000172300, 0x1, 0x1, 0x2)
        /home/orzogc/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20201006103627-071d50aec7f1/client/client.go:346 +0x85
github.com/Mrs4s/MiraiGo/client.(*QQClient).ReloadFriendList(...)
        /home/orzogc/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20201006103627-071d50aec7f1/client/client.go:333
main.initMirai(0xc00045dca0)
        /home/orzogc/src/go/acfunlive/mirai.go:107 +0x5e9
main.main()
        /home/orzogc/src/go/acfunlive/main.go:343 +0xe8d
```

**Comment by Logiase** [comment]
10月6日更新问题依旧

```
github.com/Mrs4s/MiraiGo/binary.(*TEA).encode(0x0, 0xc000340000, 0x8, 0xe8, 0xc000340000, 0x8, 0xe8)
	/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20201006103627-071d50aec7f1/binary/tea.go:124 +0x45
github.com/Mrs4s/MiraiGo/binary.(*TEA).Encrypt(0x0, 0xc00032c140, 0xda, 0x125, 0xc0000104d8, 0xc0000104d8, 0xc0003155f0)
	/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20201006103627-071d50aec7f1/binary/tea.go:44 +0x1ee
github.com/Mrs4s/MiraiGo/binary.(*Writer).EncryptAndWrite(0xc0000104d0, 0x0, 0x0, 0x0, 0xc00032c140, 0xda, 0x125)
	/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20201006103627-071d50aec7f1/binary/writer.go:68 +0x71
github.com/Mrs4s/MiraiGo/protocol/packets.BuildUniPacket.func1(0xc0000104d0)
	/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20201006103627-071d50aec7f1/protocol/packets/builders.go:35 +0x225
github.com/Mrs4s/MiraiGo/binary.(*Writer).WriteIntLvPacket(0xc000293918, 0x4, 0xc000293948)
	/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20201006103627-071d50aec7f1/binary/writer.go:74 +0x7b
github.com/Mrs4s/MiraiGo/protocol/packets.BuildUniPacket(0x8aa17e9a, 0xc000333637, 0xb65d8f, 0x1d, 0xc0000acb01, 0xc0002888a8, 0x4, 0x4, 0xc000293a84, 0x0, ...)
	/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20201006103627-071d50aec7f1/protocol/packets/builders.go:29 +0x1a5
github.com/Mrs4s/MiraiGo/client.(*QQClient).buildFriendGroupListRequestPacket(0xc0002be300, 0x960000, 0x19, 0xc00009e3f0, 0xc000035d40, 0x0)
	/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20201006103627-071d50aec7f1/client/builders.go:363 +0x54a
github.com/Mrs4s/MiraiGo/client.(*QQClient).GetFriendList(0xc0002be300, 0x4, 0xc000293c90, 0x1)
	/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20201006103627-071d50aec7f1/client/client.go:346 +0x85
github.com/Mrs4s/MiraiGo/client.(*QQClient).ReloadFriendList(...)
	/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20201006103627-071d50aec7f1/client/client.go:333
```

**Comment by Mrs4s** [comment]
这个是未处理登录错误直接调用`ReloadFriendList`导致的，最近更新了Pad协议的版本并增加了对SNS请求的处理, 请检查相关错误
